FROM golang:1.25.1-alpine AS builder

WORKDIR /app
RUN apk add --no-cache ca-certificates tzdata

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build \
    -ldflags="-s -w" \
    -trimpath \
    -o /bin/app \
    ./cmd
FROM gcr.io/distroless/static-debian12:nonroot AS production

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /bin/app /app

ENV PORT=8080 \
    GO_ENV=production \
    TZ=Asia/Tokyo
EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/app"]
